name: RulePack Tests

on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  test_rulepack:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  generate_rules:
    needs: test_rulepack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Generate rules
        run: node_modules/pingone-davinci-linter/lib/dvlint --lintRules --json
